# Config for a simple 256 -> 16 autoencoder
model:
  model_id: dcae
  sample_size: 64
  channels: 3
  latent_size: 8
  latent_channels: 16
  
  noise_decoder_inputs: 0.05
  ch_0: 32
  ch_max: 128

  encoder_blocks_per_stage: [2,2,2]
  decoder_blocks_per_stage: [2,2,2]

train:
  trainer_id: rec
  data_id: mnist

  target_batch_size: 128
  batch_size: 128

  epochs: 200

  opt: AdamW
  opt_kwargs:
    lr: 1.0e-4
    eps: 1.0e-15
    betas: [0.9, 0.95]

  loss_weights:
    latent_reg: 1.0e-6
    lpips: 0.0

  scheduler: LinearWarmup
  scheduler_kwargs:
    warmup_steps: 3000
    min_lr: 1.0e-5

  checkpoint_dir: checkpoints/v0

  sample_interval: 1000
  save_interval: 10000

wandb:
  name: shahbuland
  project: new_vaes
  run_name: v0